# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('CanmVUSB', src, depend = ['ENABLE_CANMV_USB_DEV'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
