from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src	= Glob('main.c')
src	+= Glob('mnt.c')

if GetDepend(['RT_USING_SDIO']):
    src	+= Glob('config.c')

if GetDepend(['RT_WLAN_MANAGE_ENABLE']):
    src	+= Glob('wlan_mgmt_dev.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
