# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('MemInfoDev', src, depend = ['ENABLE_CANMV_MISC_DEV'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
