# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('WlanMgmtDev', src, depend = ['ENABLE_WLAN_MGMT_DEV'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
